// <auto-generated />
using LoanMe.Catalog.Api.Application.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanMe.Catalog.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190706103020_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LoanMe.Customers.Api.Application.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            FirstName = "Juan Luis",
                            LastName = "Guerrero Minero"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            FirstName = "Francisco",
                            LastName = "Ruiz Vázquez"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            FirstName = "Eva",
                            LastName = "Perez Moreno"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            FirstName = "Maria",
                            LastName = "Serrano Sanchez"
                        });
                });

            modelBuilder.Entity("LoanMe.Customers.Api.Application.Entities.CustomerAccount", b =>
                {
                    b.Property<int>("CustomerId");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("MarkAsDefault");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomersAccount");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BankAccount = "ES12-1234-1234-1234567890",
                            MarkAsDefault = true
                        },
                        new
                        {
                            CustomerId = 2,
                            BankAccount = "ES13-4321-4321-0987654321",
                            MarkAsDefault = true
                        });
                });

            modelBuilder.Entity("LoanMe.Customers.Api.Application.Entities.CustomerAccount", b =>
                {
                    b.HasOne("LoanMe.Customers.Api.Application.Entities.Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
